############################################################################
# apps/rc_in/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

# Library only - no MAINSRC, so this registers no NSH command. It exists purely
# to define the rc_in topic that the RC publishers share.
CSRCS += rc_in.c

include $(APPDIR)/Application.mk
