############################################################################
# apps/grep/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_XXCAR_GREP_PROGNAME)
PRIORITY  = $(CONFIG_XXCAR_GREP_PRIORITY)
STACKSIZE = $(CONFIG_XXCAR_GREP_STACKSIZE)
MODULE    = $(CONFIG_XXCAR_GREP)

MAINSRC   = grep_main.c

include $(APPDIR)/Application.mk
