############################################################################
# apps/reboot/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_XXCAR_REBOOT_PROGNAME)
PRIORITY  = $(CONFIG_XXCAR_REBOOT_PRIORITY)
STACKSIZE = $(CONFIG_XXCAR_REBOOT_STACKSIZE)
MODULE    = $(CONFIG_XXCAR_REBOOT)

MAINSRC   = reboot_main.c

include $(APPDIR)/Application.mk
