############################################################################
# apps/sd_status/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_XXCAR_SD_STATUS_PROGNAME)
PRIORITY  = $(CONFIG_XXCAR_SD_STATUS_PRIORITY)
STACKSIZE = $(CONFIG_XXCAR_SD_STATUS_STACKSIZE)
MODULE    = $(CONFIG_XXCAR_SD_STATUS)

MAINSRC   = sd_status_main.c

include $(APPDIR)/Application.mk
