############################################################################
# apps/imu_cal/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

# A library only - no MAINSRC, there is no imu_cal command.
CSRCS += imu_cal.c

include $(APPDIR)/Application.mk
