############################################################################
# apps/clear/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_XXCAR_CLEAR_PROGNAME)
PRIORITY  = $(CONFIG_XXCAR_CLEAR_PRIORITY)
STACKSIZE = $(CONFIG_XXCAR_CLEAR_STACKSIZE)
MODULE    = $(CONFIG_XXCAR_CLEAR)

MAINSRC   = clear_main.c

include $(APPDIR)/Application.mk
