############################################################################
# apps/Makefile  (xxCar out-of-tree applications)
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

MENUDESC = "xxCar Applications"

include $(APPDIR)/Directory.mk
