############################################################################
# apps/uorb_msgs/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

# Library only - defines the optical_flow and distance_sensor topics for
# whichever driver publishes them and whichever consumer subscribes.
CSRCS += uorb_msgs.c

include $(APPDIR)/Application.mk
