############################################################################
# apps/sdmsc/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_XXCAR_SDMSC_PROGNAME)
PRIORITY  = $(CONFIG_XXCAR_SDMSC_PRIORITY)
STACKSIZE = $(CONFIG_XXCAR_SDMSC_STACKSIZE)
MODULE    = $(CONFIG_XXCAR_SDMSC)

MAINSRC   = sdmsc_main.c

include $(APPDIR)/Application.mk
